name: CI
on: [push, pull_request]
env:
  go-version: '1.18.x'
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          go mod download

      - name: Run tests
        run: |
          go test -v -covermode atomic -coverprofile=profile.cov ./...

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
